# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "proj"
cmake-after = """
set(CMAKE_CXX_FLAGS "-Xclang -mcmodel=large -Xclang -fno-jump-tables")
"""

[target.with_mcmodel]
type = "executable"
sources = ["src/main.cpp"]
